version: '2'
services:

  rmq1:
    image: bijukunjummen/rabbitmq-server:3.6.5
    hostname: rmq1
    environment:
      ERLANG_COOKIE: 'ck8FC0uJ9vePIhLr'
      TCP_PORTS: "5672,15672"
    ports:
      - "127.0.0.1:1234:15672"
    networks:
      - rmq_1_2
      - rmq_3_1

  rmq2:
    image: bijukunjummen/rabbitmq-server:3.6.5
    hostname: rmq2
    environment:
      ERLANG_COOKIE: 'ck8FC0uJ9vePIhLr'
      CLUSTERED: 'true'
      CLUSTER_WITH: rmq1
      TCP_PORTS: "5672"
    ports:
      - "127.0.0.1:1235:15672"
    networks:
      - rmq_1_2
      - rmq_2_3

  rmq3:
    image: bijukunjummen/rabbitmq-server:3.6.5
    hostname: rmq3
    environment:
      ERLANG_COOKIE: 'ck8FC0uJ9vePIhLr'
      CLUSTERED: 'true'
      CLUSTER_WITH: rmq1
      TCP_PORTS: "5672"
    ports:
      - "127.0.0.1:1236:15672"
    networks:
      - rmq_3_1
      - rmq_2_3

  haproxy:
    image: dockercloud/haproxy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      MODE: tcp
      LOG_LEVEL: "info"
      BALANCE: static-rr
    expose:
      - 5673
    links:
      - rmq1
      - rmq2
      - rmq3
    ports:
      - '80:80'
      - '5673:5672'
    networks:
      - default
      - rmq_1_2
      - rmq_2_3
      - rmq_3_1

networks:
  rmq_1_2:
    external:
      name: rmq_1_2
  rmq_2_3:
    external:
      name: rmq_2_3
  rmq_3_1:
    external:
      name: rmq_3_1
