version: "3"
services:
  rabbit1:
    image: rabbitmq:3-management
    hostname: rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "Rand0mStr1ng"
      RABBITMQ_NODENAME: rabbit1
      TCP_PORTS: "5672, 15672"
    volumes:
      - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
      - "./definitions.json:/etc/rabbitmq/definitions.json"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"

  rabbit2:
    image: rabbitmq:3-management
    hostname: rabbit2
    depends_on:
      - rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "Rand0mStr1ng"
      RABBITMQ_NODENAME: rabbit2
      TCP_PORTS: "5672"
    volumes:
      - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
      - "./definitions.json:/etc/rabbitmq/definitions.json"
    ports:
      - "6672:5672"
      - "35672:15672"
      - "45672:25672"
    
# rabbit3:
#    image: rabbitmq:3-management
#    hostname: rabbit3
#    depends_on:
#      - rabbit1
#    environment:
#      RABBITMQ_ERLANG_COOKIE: "Rand0mStr1ng"
#      RABBITMQ_NODENAME: rabbit3
#      TCP_PORTS: "5672"
#    volumes:
#      - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
#      - "./definitions.json:/etc/rabbitmq/definitions.json"
#    ports:
#      - "8672:5672"
#      - "55672:15672"
#      - "55772:25672"

  haproxy:
    image: dockercloud/haproxy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      MODE: tcp
      LOG_LEVEL: "info"
      BALANCE: static-rr
    expose:
      - 5673
    links:
      - rabbit1
      - rabbit2
 #     - rabbit3
    ports:
      - '80:80'
      - '5673:5672'

networks:
  default:
    external:
      name: rabbitmq-cluster
